apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo-app
  labels:
    app: platform-demo
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: platform-demo
  template:
    metadata:
      labels:
        app: platform-demo
    spec:
      containers:
      - name: platform-demo-container
        image: platform-demo  # Replace with your Docker image (e.g., your_dockerhub_username/platform-demo-app)
        ports:
        - containerPort: 5000  # Port exposed by the container
        env:
        - name: ENVIRONMENT
          value: "production"  # Example of an environment variable
