apiVersion: v1
kind: Service
metadata:
  name: platform-demo-service
spec:
  selector:
    app: platform-demo
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5000  # The port on the container
  type: LoadBalancer  # Exposes the app publicly (use ClusterIP for internal traffic only)
